routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){
    Route::get('/', function (){
        return view('admin.index');
    })->name('admin.index');
    Route::resource('users', 'UsersController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('tasks', 'TasksController');
});

Route::group(['prefix' => 'home', 'middleware' => 'auth'], function(){
    Route::get('/','HomeController@index')->name('home');
    //Route::get('/tasks','HomeController@showTasks')->name('home.tasks');
    //Route::get('/projects','HomeController@showProjects')->name('home.projects');
    Route::resource('/projects', 'MyProjectsController', ['as'=>'main']);
    Route::resource('/tasks', 'MyTasksController', ['as'=>'main']);
    Route::post('/tasks/attachUser', 'MyTasksController@attachUser')->name('main.tasks.attachUser');
    Route::post('/tasks/comment', 'MyTasksController@comment')->name('main.tasks.comment');
    Route::post('/tasks/setProgress', 'MyTasksController@setProgress')->name('main.tasks.setProgress');
    Route::post('/myUser/update', 'MyUserController@update')->name('main.myUser.update');
});

Auth::routes();

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{   //Mass assignable attributes.
    protected $fillable = ['alias', 'name', 'description', 'avatar', 'status', 'initial_date', 'final_date', 'leader_user_id'];
    // Name in MySQL table
    protected $table = 'projects';

    public function user(){
        return $this->belongsTo('App\User', 'leader_user_id');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\User;
use App\Http\Requests\ProjectRequest;
use \DateTime;

class ProjectsController extends Controller
{
    public function index(){
        $projects = Project::orderBy('name', 'asc')->paginate(5);
        return view('admin.projects.index')->with('projects', $projects);
    }

    public function create(){
        
        $users = User::orderBy('name', 'asc')->get();
        $options = array();
        foreach ($users as $user) {
            $options[$user->id] = $user->name;
        }
        return view('admin.projects.create', ['options'=>$options]);
    }

    public function store(ProjectRequest $request){

        $initialDate = new DateTime($request->initial_date);
        $finalDate = new DateTime($request->final_date);

        if($initialDate < $finalDate){
            $project = new Project($request->all());
            if($request->file('avatar')){
                $file = $request->file('avatar');
                $name = 'project_avatar'.time().'.'.$file->getClientOriginalExtension();
                $path = public_path().'/imgs/project/';
                $file->move($path, $name);
                $project->avatar = $name;
            }
            $project->save();

            return redirect()->route('projects.index');
        }else{
            return redirect()->route('projects.create')->withErrors('La fecha inicial debe ser anterior a la final.');
        }
    }

    public function edit($id){
        $users = User::orderBy('name', 'asc')->get();
        $options = array();
        foreach ($users as $user) {
            $options[$user->id] = $user->name;
        }
        $project = Project::find($id);
        return view('admin.projects.edit')->with(['project' => $project, 'options' => $options]);
    }

    public function update($id, Request $request){
        $project = Project::find($id);
        $aux = $project->avatar;
        $project->fill($request->all());
        $project->avatar = $aux;

        if($request->file('avatar')){
            $file = $request->file('avatar');
            $name = 'project_avatar'.time().'.'.$file->getClientOriginalExtension();
            $path = public_path().'/imgs/project/';
            unlink($path.$project->avatar);
            $file->move($path, $name);
            $project->avatar = $name;
        }
       
        $project->save();
        return redirect()->route('projects.index');
    }

    public function destroy($id){
        $project = Project::find($id);
        $path = public_path().'/imgs/project/';
        unlink($path.$project->avatar);
        $project->delete();

        return redirect()->route('projects.index');
    }
}

resources/views/main/projects/create.blade.php
@extends('main.home')

@section('title', '- Creacion de proyectos')

@section('content')
    <div>
    @if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        @foreach ($errors->all() as $e)
            <li>{{$e}}</li>
        @endforeach
    </div>
    @endif
    
    {!! Form::open(['route' => 'main.projects.store', 'method' => 'POST', 'files' => true]) !!}
        <div class="form-group">
            {!! Form::label('alias', 'Alias') !!}
            {!! Form::text('alias',null, ['class' => 'form-control', 'placeholder' => 'Ingrese un alias (único)', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description', 'Descripcion') !!}
            {!! Form::textarea('description',null, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('status', 'Estado') !!}
            {!! Form::text('status',null, ['class' => 'form-control', 'placeholder' => 'Ingrese el estado', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('initial_date', 'Fecha inicial') !!}
            {!! Form::date('initial_date',null, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('final_date', 'Fecha final') !!}
            {!! Form::date('final_date',null, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('avatar', 'Avatar') !!}
            {!! Form::file('avatar'); !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Registrar', ['class'=>'btn btn-primary']) !!}
        </div>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/main/projects/edit.blade.php
@extends('main.home')

@section('title', '- '.$project->name)

@section('content')

    @if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        @foreach ($errors->all() as $e)
            <li>{{$e}}</li>
        @endforeach
    </div>
    @endif

    <div>
        <img src="/imgs/project/{{$project->avatar}}" alt="" class="project_avatar">
    </div>
    
    {!! Form::open(['route' => ['main.projects.update', $project], 'method' => 'PUT', 'files' => true]) !!}
        <div class="form-group">
            {!! Form::label('alias', 'Alias') !!}
            {!! Form::text('alias',$project->alias, ['class' => 'form-control', 'placeholder' => 'Ingrese un alias (único)', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('name',$project->name, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description', 'Descripcion') !!}
            {!! Form::text('description',$project->description, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('status', 'Estado') !!}
            {!! Form::text('status',$project->status, ['class' => 'form-control', 'placeholder' => 'Ingrese el estado', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('initial_date', 'Fecha inicial') !!}
            {!! Form::date('initial_date',$project->initial_date, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('final_date', 'Fecha final') !!}
            {!! Form::date('final_date',$project->final_date, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('avatar', 'Avatar') !!}
            {!! Form::file('avatar'); !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Agregar', ['class'=>'btn btn-primary']) !!}
        </div>
    {!! Form::close() !!}
@endsection

resources/views/main/projects/index.blade.php
@extends('main.home')

@section('title', '- Mis proyectos')

@section('content')
<div style="width:100%; padding:10px">
    <div class="main-buttons">
        <form method="get" action="{{route('main.projects.create')}}">
        <button type="submit" class="btn btn-success">
            <img src= {{ @asset('/svg/plus.svg') }} alt="Mis proyectos">
        </button>
        </form>
    </div>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Alias</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripción</th>
                <th scope="col">Estado</th>
                <th scope="col">Fecha inicial</th>
                <th scope="col">Fecha final</th>
                <th scope="col">Editar</th>
                <th scope="col">Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($myProjects as $project)
                <tr>
                    <th scope="row">{{ $project->alias }}</th>
                    <td>{{ $project->name }}</td>
                    <td>{{ $project->description }}</td>
                    <td>{{ $project->status }}</td>
                    <td>{{ $project->initial_date }}</td>
                    <td>{{ $project->final_date }}</td>
                    <td>
                        <a href="{{ route('main.projects.edit', $project->id) }}">
                            <button class="btn btn-info">
                                <img src= {{ @asset('/svg/pencil.svg') }} alt="Editar">
                            </button>
                        </a>
                    </td>
                    <td>
                        <form action="{{ route('main.projects.destroy', $project->id) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">
                                <img src= {{ @asset('/svg/trash.svg') }} alt="Eliminar">
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection