routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){
    Route::get('/', function (){
        return view('admin.index');
    })->name('admin.index');
    Route::resource('users', 'UsersController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('tasks', 'TasksController');
});

Route::group(['prefix' => 'home', 'middleware' => 'auth'], function(){
    Route::get('/','HomeController@index')->name('home');
    //Route::get('/tasks','HomeController@showTasks')->name('home.tasks');
    //Route::get('/projects','HomeController@showProjects')->name('home.projects');
    Route::resource('/projects', 'MyProjectsController', ['as'=>'main']);
    Route::resource('/tasks', 'MyTasksController', ['as'=>'main']);
    Route::post('/tasks/attachUser', 'MyTasksController@attachUser')->name('main.tasks.attachUser');
    Route::post('/tasks/comment', 'MyTasksController@comment')->name('main.tasks.comment');
    Route::post('/tasks/setProgress', 'MyTasksController@setProgress')->name('main.tasks.setProgress');
    Route::post('/myUser/update', 'MyUserController@update')->name('main.myUser.update');
});

Auth::routes();

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //Mass assignable attributes.
    protected $fillable = ['alias', 'name', 'description', 'status', 'initial_date', 'final_date'];
    // Name in MySQL table
    protected $table = 'tasks';

    public function comment(){
        return $this->hasMany('App\Comment', 'parent_task_id');
    }

    public function task (){
        return $this->hasMany('App\Task', 'parent_task_id');
    }

    public function user(){
        return $this->belongsToMany('App\User', 'user_task', 'task_id', 'user_id');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\Http\Requests\TaskRequest;
use \DateTime;

class TasksController extends Controller
{
    public function index(){
        $tasks = Task::orderBy('name', 'asc')->paginate(5);
        return view('admin.tasks.index')->with('tasks', $tasks);
    }

    public function create(){
        return view('admin.tasks.create');
    }

    public function store(TaskRequest $request){
        $initialDate = new DateTime($request->initial_date);
        $finalDate = new DateTime($request->final_date);

        if($initialDate < $finalDate){
            $task = new Task($request->all());
            $task->save();

            return redirect()->route('tasks.index');
        }else{
            return redirect()->route('tasks.create')->withErrors('La fecha inicial debe ser anterior a la final.');
        }
    }

    public function edit($id){
        $task = Task::find($id);
        return view('admin.tasks.edit')->with('task', $task);
    }

    public function update($id, Request $request){
        $task = Task::find($id);
        $task->fill($request->all());
       
        $task->save();
        return redirect()->route('tasks.index');
    }

    public function destroy($id){
        $task = Task::find($id);
        $task->delete();

        return redirect()->route('tasks.index');
    }
}

resources/views/admin/tasks/create.blade.php
@extends('admin.main')

@section('title', 'Creacion de tareas')

@section('content')

    @if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        @foreach ($errors->all() as $e)
            <li>{{$e}}</li>
        @endforeach
    </div>
    @endif
    
    {!! Form::open(['route' => 'main.tasks.store', 'method' => 'POST']) !!}
        <div class="form-group">
            {!! Form::label('alias', 'Alias') !!}
            {!! Form::text('alias',null, ['class' => 'form-control', 'placeholder' => 'Ingrese un alias (único)', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description', 'Descripcion') !!}
            {!! Form::text('description',null, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('status', 'Estado') !!}
            {!! Form::text('status',null, ['class' => 'form-control', 'placeholder' => 'Ingrese el estado', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('initial_date', 'Fecha inicial') !!}
            {!! Form::date('initial_date',null, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('final_date', 'Fecha final') !!}
            {!! Form::date('final_date',null, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Registrar', ['class'=>'btn btn-primary']) !!}
        </div>
    {!! Form::close() !!}
@endsection

resources/views/admin/tasks/edit.blade.php
@extends('admin.main')

@section('title', $task->name)

@section('content')

    @if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        @foreach ($errors->all() as $e)
            <li>{{$e}}</li>
        @endforeach
    </div>
    @endif
    
    {!! Form::open(['route' => ['tasks.update', $task], 'method' => 'PUT']) !!}
        <div class="form-group">
            {!! Form::label('alias', 'Alias') !!}
            {!! Form::text('alias',$task->alias, ['class' => 'form-control', 'placeholder' => 'Ingrese un alias (único)', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('name',$task->name, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description', 'Descripcion') !!}
            {!! Form::text('description',$task->description, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('status', 'Estado') !!}
            {!! Form::text('status',$task->status, ['class' => 'form-control', 'placeholder' => 'Ingrese el estado', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('initial_date', 'Fecha inicial') !!}
            {!! Form::date('initial_date',$task->initial_date, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::label('final_date', 'Fecha final') !!}
            {!! Form::date('final_date',$task->final_date, ['class' => 'form-control', 'required'] ) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Actualizar', ['class'=>'btn btn-primary']) !!}
        </div>
    {!! Form::close() !!}
@endsection

resources/views/admin/tasks/index.blade.php
@extends('admin.main')
@section('title', 'Todas las tareas')

@section('content')
    <div class="main-buttons">
        <form method="get" action="{{route('main.tasks.create')}}">
        <button type="submit" class="btn btn-success">
            <img src= {{ @asset('/svg/plus.svg') }} alt="Agregar nueva tarea">
        </button>
        </form>
    </div>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Alias</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripción</th>
                <th scope="col">Estado</th>
                <th scope="col">Fecha inicial</th>
                <th scope="col">Fecha final</th>
                <th scope="col">Usuarios asignados</th>
                <th scope="col">Editar</th>
                <th scope="col">Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($tasks as $task)
                <tr>
                    <th scope="row">{{ $task->alias }}</th>
                    <td>{{ $task->name }}</td>
                    <td>{{ $task->description }}</td>
                    <td>{{ $task->status }}</td>
                    <td>{{ $task->initial_date }}</td>
                    <td>{{ $task->final_date }}</td>
                    <td>
                        @foreach ($task->user as  $asigned_user)
                            {{ $asigned_user->name }}
                        @endforeach
                    </td>
                    <td>
                        <a href="{{ route('main.tasks.edit', $task->id) }}">
                            <button class="btn btn-info">
                                <img src= {{ @asset('/svg/pencil.svg') }} alt="Editar">
                            </button>
                        </a>
                    </td>
                    <td>
                        <form action="{{ route('main.tasks.destroy', $task->id) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">
                                <img src= {{ @asset('/svg/trash.svg') }} alt="Eliminar">
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pagination_links row">
            {{ $tasks->links() }}
    </div>
@endsection